version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=amazona-dev
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongodb_data:
